# Builds the production version of the app
name: build-prod

on:
  workflow_call:

jobs:
  prod:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
      - uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4
        with:
          node-version: "lts/*"
          cache: "npm"
      - name: NPM install
        run: npm ci
      - name: Install roku module dependencies
        run: npm run ropm
      - name: Find and save major_version from manifest
        if: github.event.inputs.targetBranch == 'bugfix'
        run: awk 'BEGIN { FS="=" } /^major_version/ { print "majorVersion="$2; }' manifest >> $GITHUB_ENV
      - name: Find and save minor_version from manifest
        if: github.event.inputs.targetBranch == 'bugfix'
        run: awk 'BEGIN { FS="=" } /^minor_version/ { print "MinorVersion="$2; }' manifest >> $GITHUB_ENV
      - name: Find and save build_version from manifest
        if: github.event.inputs.targetBranch == 'bugfix'
        run: awk 'BEGIN { FS="=" } /^build_version/ { print "BuildVersion="$2; }' manifest >> $GITHUB_ENV
      - name: Build app for production
        run: npm run build-prod
      - uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4
        with:
          name: JellyRock-v${{ env.majorVersion }}.${{ env.MinorVersion }}.${{ env.BuildVersion }}-${{ github.sha }}
          path: ${{ github.workspace }}/build/staging
          if-no-files-found: error
