name: Automation 🤖

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

on:
  push:
    branches:
      - master
  pull_request_target:
    types: [opened, synchronize]

jobs:
  label:
    # don't run job on forks
    if: github.repository == 'cewert/jellyrock'
    name: Labeling 🏷️
    runs-on: ubuntu-latest
    steps:
      - name: Check all PRs for merge conflicts ⛔
        uses: eps1lon/actions-label-merge-conflict@releases/2.x
        with:
          dirtyLabel: "merge-conflict"
          commentOnDirty: "This pull request has merge conflicts. Please resolve the conflicts so the PR can be reviewed. Thanks!"
          repoToken: ${{ secrets.JELLYROCK_BOT_TOKEN }}
