name: Automation 🤖

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

on:
  push:
    branches:
      - master
  pull_request_target:
    types: [opened, synchronize]

jobs:
  project:
    # don't run job on forks
    if: github.repository == 'cewert/jellyfin-roku'
    name: Project board 📊
    runs-on: ubuntu-latest
    steps:
      - uses: alex-page/github-project-automation-plus@303f24a24c67ce7adf565a07e96720faf126fe36 # v0.9.0
        if: ${{ github.event_name == 'pull_request_target' }}
        continue-on-error: true
        with:
          project: Ongoing development
          column: In progress
          repo-token: ${{ secrets.CEWERT_BOT_TOKEN }}
  label:
    # don't run job on forks
    if: github.repository == 'cewert/jellyfin-roku'
    name: Labeling 🏷️
    runs-on: ubuntu-latest
    steps:
      - name: Check all PRs for merge conflicts ⛔
        uses: eps1lon/actions-label-merge-conflict@releases/2.x
        with:
          dirtyLabel: "merge-conflict"
          commentOnDirty: "This pull request has merge conflicts. Please resolve the conflicts so the PR can be reviewed. Thanks!"
          repoToken: ${{ secrets.CEWERT_BOT_TOKEN }}
