name: Build

on:
  push:
    branches-ignore:
      - "v*.*.*" # Version branches handled by release workflow
  pull_request:
    types: [opened]

jobs:
  dev:
    uses: ./.github/workflows/_build-app.yml
    with:
      build_type: dev
      upload_zip: true # Always upload ZIP artifacts for download
      create_github_release: false
    secrets: inherit
  prod:
    uses: ./.github/workflows/_build-app.yml
    with:
      build_type: prod
      upload_zip: true # Always upload ZIP artifacts for download
      create_github_release: false
    secrets: inherit
