name: Universal Build

on:
  push:
    branches-ignore:
      - "v*.*.*" # Version branches handled by release workflow
  pull_request:
    types: [opened]

jobs:
  build-dev:
    uses: ./.github/workflows/_build-app.yml
    with:
      build_type: dev
      upload_zip: true # Always upload ZIP artifacts for download
      create_github_release: false
    secrets: inherit
  build-prod:
    uses: ./.github/workflows/_build-app.yml
    with:
      build_type: prod
      upload_zip: true # Always upload ZIP artifacts for download
      create_github_release: false
    secrets: inherit
