name: build-dev

on:
  pull_request:
      types: [opened, synchronize]
  push:
    branches:
      - main

jobs:
  dev:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5
      - uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4
        with:
          node-version: "lts/*"
          cache: "npm"
      - name: NPM install
        run: npm ci
      - name: Build app
        run: npm run build
      - uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4
        with:
          name: JellyRock-dev-${{ github.sha }}
          path: ${{ github.workspace }}/build/staging
          if-no-files-found: error
