name: lint-brightscript
on:
  pull_request:
    paths:
      - "**/*.brs"
      - "**/*.bs"

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@master
        with:
          node-version: "lts/*"
          cache: "npm"
      - run: npm ci
      - run: npx ropm install
      - run: npm run validate
      - run: npm run check-formatting
