name: Roku static analysis

on:
  workflow_dispatch: # allow manual start
  push:
    branches:
      - "v*.*.*" # e.g. v1.0.0, v2.1.3

jobs:
  static:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5
      - uses: actions/setup-node@2028fbc5c25fe9cf00d9f06a71cc4710d4507903 # v6
        with:
          node-version: "lts/*"
          cache: "npm"
      - name: Cache ropm dependencies
        uses: actions/cache@0057852bfaa89a56745cba8c7296529d2fc39830 # v4.3.0
        with:
          path: |
            source/roku_modules
            components/roku_modules
          key: ropm-${{ hashFiles('package.json', 'package-lock.json') }}
          restore-keys: ropm-
      - name: NPM install
        run: npm ci
      - name: Build app for production
        run: npm run build:prod
      - name: Setup Java
        uses: actions/setup-java@dded0888837ed1f317902acf8a20df0ad188d165 # v5
        with:
          distribution: "temurin"
          java-version: "21"
      - name: Cache Static Channel Analysis CLI
        uses: actions/cache@0057852bfaa89a56745cba8c7296529d2fc39830 # v4.3.0
        id: cache-sca
        with:
          path: sca-cmd
          key: sca-cmd-${{ hashFiles('sca-cmd/bin/sca-cmd') }}
          restore-keys: sca-cmd-
      - name: Download the Static Channel Analysis CLI
        if: steps.cache-sca.outputs.cache-hit != 'true'
        run: |
          curl -sSL "https://devtools.web.roku.com/static-channel-analysis/sca-cmd.zip" -o sca-cmd.zip
          unzip sca-cmd.zip
      - name: Run Roku Static Analysis
        run: ./sca-cmd/bin/sca-cmd ${{ github.workspace }}/build --exit error
