name: roku-analysis

on:
  push:
    branches:
      - master

jobs:
  static:
    # don't run job on forks
    if: github.repository == 'cewert/jellyfin-roku'
    uses: ./.github/workflows/_roku-analysis.yml
