name: roku-analysis

on:
  push:
    branches:
      - main
    paths-ignore:
      - '.github/**'
      - '.vscode/**'
      - 'docs/**'
      - 'locale/**'
      - 'scripts/**'
      - 'unit-tests/**'

jobs:
  static:
    # don't run job on forks
    if: github.repository == 'cewert/jellyrock'
    uses: ./.github/workflows/_roku-analysis.yml
