name: Roku static analysis

on:
  workflow_dispatch: # allow manual start
  push:
    branches:
      - "v*.*.*" # e.g. v1.0.0, v2.1.3

jobs:
  static:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5
      - uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4
        with:
          node-version: "lts/*"
          cache: "npm"
      - name: Cache ropm dependencies
        uses: actions/cache@v4
        with:
          path: |
            source/roku_modules
            components/roku_modules
            .ropm
          key: ropm-${{ hashFiles('package.json', 'package-lock.json') }}
          restore-keys: ropm-
      - name: Cache BrighterScript build artifacts
        uses: actions/cache@v4
        with:
          path: |
            .brighterscript
            node_modules/.cache
          key: brighterscript-prod-${{ hashFiles('bsconfig-prod.json', 'manifest', 'source/**/*.*', 'components/**/*.*', 'images/**/*.*', 'locale/**/*.*', 'settings/**/*.*') }}
          restore-keys: |
            brighterscript-prod-${{ hashFiles('bsconfig-prod.json', 'bsconfig.json') }}-
            brighterscript-prod-
            brighterscript-dev-${{ hashFiles('bsconfig.json') }}-
            brighterscript-dev-
            brighterscript-
      - name: NPM install
        run: npm ci
      - name: Build app for production
        run: npm run build-prod
      - name: Setup Java
        uses: actions/setup-java@dded0888837ed1f317902acf8a20df0ad188d165 # v5
        with:
          distribution: "temurin"
          java-version: "21"
          cache: "gradle" # Cache Gradle dependencies if any
      - name: Cache Static Channel Analysis CLI
        uses: actions/cache@v4
        id: cache-sca
        with:
          path: sca-cmd
          key: sca-cmd-${{ hashFiles('sca-cmd/bin/sca-cmd') }}
          restore-keys: sca-cmd-
      - name: Download the Static Channel Analysis CLI
        if: steps.cache-sca.outputs.cache-hit != 'true'
        run: |
          curl -sSL "https://devtools.web.roku.com/static-channel-analysis/sca-cmd.zip" -o sca-cmd.zip
          unzip sca-cmd.zip
      - name: Run Roku Static Analysis
        run: ./sca-cmd/bin/sca-cmd ${{ github.workspace }}/build/staging --exit error
